### ISSUE TITLE
Unexpected behaviour with reply all

### ISSUE THREAD

**Issue by mbrubake** [dennisverspuij/tb-correctidentity#19]
I have multiple email address aliases configured for detection with a specific identity.  However, when I receive an email at an alias and I hit reply all, it still includes those addresses in the recipient list for replies.  I'm not sure if this is a bug, expected behaviour or I'm doing something wrong.  The aliases are old email addresses which forward to a new address and I'd like to avoid constantly sending myself duplicate emails.

This is with TB 91.11 and plugin version 2.1.1

**Comment by ldreier** [comment]
I think (if I understood your description correctly) that I have seen this behaviour already with older versions.
Is the understanding correct that in your "reply all" message the email address appears (after being changed by this add-on) both in "from" and one of "cc" or "to"?
For that case I added a patch to this repository some minutes ago.
Could you test "correct_identity_latest.xpi" on https://github.com/dennisverspuij/tb-correctidentity/releases/tag/latest if this fixes your problem?

**Comment by ldreier** [comment]
Fix is part of Release v2.3.2
