### ISSUE TITLE
feature request: search for recipient in 'Received: ...' header

### ISSUE THREAD

**Issue by spi43984** [dennisverspuij/tb-correctidentity#21]
If mail gets forwarded from one to another account the Envelope-To address might be a different one then the original mail address the mail was sent to.

Usually the original recipient mail address still can be found in one of the /^Received: from.*/ lines.

Please check for the available identities also in these received header lines.

**Comment by ldreier** [comment]
@spi43984:
Currently the add-on uses the "recipients" field from the MessageHeader structure: [MessageHeader](https://webextension-api.thunderbird.net/en/latest/messages.html#messages-messageheader)
In the code: [source](https://github.com/dennisverspuij/tb-correctidentity/blob/acf489c85bc449b555431807fcd7909e84cefb69/scripts/background-script.js#L532).
Seems that no other field from MessageHeader contains the information you want to look at? This would make it difficult to collect the information within the webExtension framework.

**Comment by alexolog** [comment]
It would be better to use [`getFull(messageId)`](https://webextension-api.thunderbird.net/en/latest/messages.html#getfull-messageid) instead and check other headers, preferably configurable.

The header that I used with old Virtual Identity add-on was `X-Delivered-to`, it consistently gave me the best results.

**Comment by spi43984** [comment]
> It would be better to use [`messages.getFull(messageId)`](https://webextension-api.thunderbird.net/en/latest/messages.html#getfull-messageid) instead and check other headers, preferably configurable.
> 
> The header that I used with old Virtual Identity add-on was `X-Delivered-to`, it consistently gave me the best results.

Just checked with mails from mailing listserver - they don't contain a `X-Delivered-to` header. So the only way to determine the right recipient address would be from a 'Received: ' header.

**Comment by alexolog** [comment]
The suggestion was to make it configurable.  That header was added by my email provider, yours may add different ones.  The Virtual Identity add-on author recognized that and allowed the user to specify what headers to check.

**Comment by spi43984** [comment]
> The suggestion was to make it configurable. That header was added by my email provider, yours may add different ones. The Virtual Identity add-on author recognized that and allowed the user to specify what headers to check.

That would be a great feature.

**Comment by alexolog** [comment]
I have email accounts with several providers so I could run a quick check.

1) Using the `recipients` list will not work if your address was specified in the `CC` or `BCC`.

2) The `for` part of the `Received:` header is optional.  Some machines include it, other do not.  I have found several emails on Yahoo in which none of those headers included it.

3) Yahoo adds the `X-Apparently-To:` header.

4) Fastmail adds the `X-Delivered-to:` header.

5) Gmail adds the `Delivered-To:` header.

Bottom line, there is no one header that can be relied on, so the best solution is to obtain the full list of headers from [`messages.getFull(messageId)`](https://webextension-api.thunderbird.net/en/latest/messages.html#getfull-messageid) and make the choice user-configurable.

[Virtual Identity](https://github.com/absorb-it/Virtual-Identity) allowed specifying multiple headers to look in, with complex resolution/precedence rules, but I believe it is an overkill.  Still, it is open source, so some code can be copied.

Unfortunately I am not familiar with JS or add-on writing.

**Comment by spi43984** [comment]
> so the best solution is to obtain the full list of headers from [`messages.getFull(messageId)`](https://webextension-api.thunderbird.net/en/latest/messages.html#getfull-messageid) and make the choice user-configurable.

Or see if the user's email address is found in any of these headers - they could be prioritized, like if found in recipients don't care for the others and so on.

**Comment by alexolog** [comment]
> Or see if the user's email address is found in any of these headers - they could be prioritized, like if found in recipients don't care for the others and so on.

Unfortunately, when you are dealing with aliases, redirections, etc. you can have different addresses in those headers.  The trivial example is `From:` and `To:`, but there can be others.  For example, `X-Resolved-to:` and `X-Delivered-to:` are different in Fastmail, and then there's `X-Mail-from:`...

Better let the user choose which ones to use.

**Comment by spi43984** [comment]
> Better let the user choose which ones to use.

But how can that be achieved? The user knows what email address he is using with his identity. But he doesn't know in what header this email address might be included. So the user only could afterwards add another header to the config to hope for the next email to arrive have this header included. In the end the user would end up adding most headers to the config file.

So one could just start searching all headers for the identity's email address If there are several identities and one of their email addresses is included in the recipient header, that identity wins. Then look in the next header and so on.

**Comment by ldreier** [comment]
I added to the master branch a console logging of the "headers" returned by getFull() [pre release](https://github.com/dennisverspuij/tb-correctidentity/releases/tag/latest). The resulting .xpi file can be found [here](https://github.com/dennisverspuij/tb-correctidentity/releases/download/latest/correct_identity_latest.xpi).
You would need to install the add on from that xpi file an look into the debug console. (debug addons ... examine).
The "headers" list has lowercase "keys" (like "received") and the list entries are each arrays of the (maybe multiple) occurrence values of the "key" in the mail header.

Seems that the Virtual Identity add-on has both "key" and "array index" configurable. If no index is given, all occurrences are searched.

So for this addon here an implementation could look like:
- Make multiple "key" and "index" pairs configurable (a single global configuration for all accounts)
- Empty index means "take all entries found with key"
- append all resulting array entries to the "origRecipientsList"

Together with the current implementation, this concatenated origRecipientsList would be searched for the known identities and the found identity would be used as "From" when answering the message.

Please comment.

**Comment by spi43984** [comment]
> Please comment.

Ok, checked that with some mailling listserver mails. 

I see in headers all the key pairs, especially the received headers with the right email address in it.

For one mailing list email my email address got pulled from the headers and put into the origRecipientsList array, for another mailing list email I saw my email address in one of the headers key pairs but it wasn't put into the origRecipientsList.

**Comment by alexolog** [comment]
Parsing issue maybe?

**Comment by spi43984** [comment]
> Parsing issue maybe?

Probably - in the received header the email address is included in brackets <xxx@xxx.xxx>, e. g.

`"from talvi.dovecot.org ([94.237.105.223]) by mx-ha.gmx.net (mxgmx114 [212.227.17.5]) with ESMTPS (Nemesis) id 1234-5678901234-567890 for <xxx@xxx.xxx>; Thu, 10 Aug 2020 12:00:00 +0000"`

Checked with another email - email address from received isn't copied to origRecipientsList.
Checked with original mail where I thought it got copied - the email address was included in another header as well so it might got copied from there.

To ease debugging - could you please add to origRecipientsList where the email address got copied from?

**Comment by ldreier** [comment]
@spi43984 Just to clarify. The origRecipientsList is still only taken from method described in the [post above](https://github.com/dennisverspuij/tb-correctidentity/issues/21#issuecomment-1212289188).

Just the debug log was added for getFull().headers

But seems that this is a direction we could go.

**Comment by spi43984** [comment]
> @spi43984 Just to clarify. The origRecipientsList is still only taken from method described in the [post above](https://github.com/dennisverspuij/tb-correctidentity/issues/21#issuecomment-1212289188).
> 
> Just the debug log was added for getFull().headers
> 
> But seems that this is a direction we could go.

Ah good. Missed that. Then it explains it...

**Comment by ldreier** [comment]
@spi43984 An initial implementation is committed to the master branch and available now in [pre release](https://github.com/dennisverspuij/tb-correctidentity/releases/tag/latest). The resulting .xpi file can be again found [here](https://github.com/dennisverspuij/tb-correctidentity/releases/download/latest/correct_identity_latest.xpi).

Compared to the proposal above, I chose to "prepend" the results of the headers to the "origRecipientsList". By this the results from the additional headers have priority over the "recipients" used before.

The additional fields can be configured at the bottom of the configuration page. The hover-over tooltip contains the description of the syntax.

Debug logs are not further extended, but contain both the headers from getFull(msgId) and the resulting origRecipientsList.

Please test and comment.

**Comment by spi43984** [comment]
> Compared to the proposal above, I chose to "prepend" the results of the headers to the "origRecipientsList". By this the results from the additional headers have priority over the "recipients" used before.
> 
> The additional fields can be configured at the bottom of the configuration page. The hover-over tooltip contains the description of the syntax.

Ok, tested it. The one mail from the mailing list containing my mail address just in the received header worked very well. The other mails as well - even if there was none or a wrong entry (like xxxx) at the bottom of the configuration.

For my understanding: at the bottom of the conf page configured headers are additionally searched for the mail address? The default headers (To:? Envelope-To?) are searched every time, even if the config is empty? The additionally configured headers win over the default ones?

Is there a way to configure "search all headers" like "/.*/"?

Thanks very much for the change! It works very well for me at it is right now.

**Comment by ldreier** [comment]
@spi43984 Your understanding is correct.
About the "default headers" I assume that this is just the "to" header. (I use, as mentioned in earlier messages, the "recipients" field of the MessageHeader structure, where the documentation states is just "to")

About "search all headers" option:
- It is not implemented
- "all headers" is a lot of garbage information...
- I also assume, that the "final" destination identity of your Inbox is also somewhere mentioned. So searching in "all" may also result in the Inbox identity which is maybe not what you want. (That is also the reason why the "additional headers" win over the default recipients)

**Comment by spi43984** [comment]
Ok, understood. As said that works very well for me. If I had one more wish free I'd like some quick button so I could add the config screen as a quick button to TB's menu bar... In that case I could add new headers really fast... But probably there won't be such a huge need anymore as with some additional header most use cases will be covered. Again - thanks for the change!

**Comment by alexolog** [comment]
I feel a bit guilty for mentioning Virtual Identity every other post, but I only do that because its developer put a lot of thought and effort into many of those questions and given that the code is open source and on Github, it is possible to check how they went about addressing them and decide if we want to use a similar approach (of course, that add-on targeted a different framework, so a direct 1-to-1 comparison, is not possible).

I tend to agree that searching all headers is not a good idea, for that same reason, but also because there can be clashes with forwarding, aliases and other rules.  For example, the email main address I get from my provider is `myaddress@provider.example`, but I have set up aliases like `someaddress@providersotherdomain.example`, as well as `whatever@mypersonaldomain.example`.  I also have email forwarded from my gmail, outlook, yahoo, etc. accounts, so it is not uncommon for the full collection of headers to have 3 or more different email addresses, all of which may have an identity associated with them, or resolve to the same wildcard,

Additional questions:
* Some headers' values consist of nothing but an email address, while others (like `received:`) may have other text in them.  Parsing the email address may be [non-trivial](https://en.wikipedia.org/wiki/Email_address).
* Are multiple wildcard identities supported?  (E.g., `*@mydomain.example` and `*@alsomydomain.example`)

**Comment by spi43984** [comment]
> For example, the email main address I get from my provider is `myaddress@provider.example`, but I have set up aliases like `someaddress@providersotherdomain.example`, as well as `whatever@mypersonaldomain.example`. I also have email forwarded from my gmail, outlook, yahoo, etc. accounts, so it is not uncommon for the full collection of headers to have 3 or more different email addresses, all of which may have an identity associated with them, or resolve to the same wildcard,

Wouldn't that mean that unique settings are required per identity and not one set globally?

**Comment by alexolog** [comment]
What I meant was that I would like to reply from the same address that the email was originally sent to, even if it ended up being delivered to a different one.

**Comment by ldreier** [comment]
@alexolog
Have you checked if the "Additional mail headers" configuration works also for you?

For finding the original recipient the addon checks all "identities" configured for that "account" (using Thunderbird terminology) against the "origRecipientsList".
The origRecipientsList consists of the header fields from "Additional mail headers" and the "to" recipients

Each entry in origRecipientsList is checked if it **contains** any of the identity plain email address. The first match is taken.

-So no exact match is needed
-"Additional mail headers" are searched one by one if present. If not present the next one is searched. So just put there all the headers where the original recipients' email address could appear.

**Comment by spi43984** [comment]
> What I meant was that I would like to reply from the same address that the email was originally sent to, even if it ended up being delivered to a different one.

After seeing the discussion on Virtual Identity I now think to understand that you want to get as from address that address you originally sent the email from even if it is not configured as an identity?

Like there are the identities
alpha@beta.com
gamma@zeta.com

and you sent an email with the from address alpha+20220818114653@beta.com and you want to reply to an email you got at this address again with alpha+20220818114653@beta.com and not alpha@beta.com. Correct?

**Comment by alexolog** [comment]
Can somebody please summarize the improvements that this will deliver over just using the wildcard identity in stock TB102?

**Comment by spi43984** [comment]
> Can somebody please summarize the improvements that this will deliver over just using the wildcard identity in stock TB102?

What is the wildcard identity?

**Comment by alexolog** [comment]
This:
https://i.stack.imgur.com/LsoOp.png

Taken from https://superuser.com/a/1690013/83314

**Comment by spi43984** [comment]
> This: https://i.stack.imgur.com/LsoOp.png
> 
> Taken from https://superuser.com/a/1690013/83314

ok, but can RegEx be used here? Or just one expression?

**Comment by alexolog** [comment]
Regex for what?

**Comment by spi43984** [comment]
> Regex for what?

Multiple mail addresses

**Comment by alexolog** [comment]
Don't think it does.  The format is `*.example.tld` but if the number of domains is small, you should be able to create identities for each domain (which is infinitely better than an identity for each address).

I may be wrong though, haven't used it myself.

**Comment by spi43984** [comment]
> Don't think it does. The format is `*.example.tld` but if the number of domains is small, you should be able to create identities for each domain (which is infinitely better than an identity for each address).
> 
> I may be wrong though, haven't used it myself.

It seems easier and quicker to me to add additional addresses into the add-on than creating new identities with all relevant settings. I'd appreciate the add-on to be published as is - new features still can be added in the next release.

**Comment by ldreier** [comment]
I will go for a release.
Before that, I will update at least the German translation of the new feature ("additional header fields") and add some description to the README for the recent changes.

**Comment by ldreier** [comment]
The version v2.2.1 was sent to the Thunderbird add-on release process and is waiting for approval.

**Comment by ldreier** [comment]
Included in released version 2.2.1, which is now available on thunderbird addon web site.
