### ISSUE TITLE
feature request: quick button for config changes

### ISSUE THREAD

**Issue by spi43984** [dennisverspuij/tb-correctidentity#22]
To add additional mail addresses to the config I need to open the addon list in TB, then find the  Correct Identity addon and hit the settings button to change the settings.

I'd appreciate a button I could add to one of TB's icon/menu bars for quickly open the config editor.
I tried to edit the bars but couldn't find any icon for Correct Identity.

**Comment by ldreier** [comment]
![grafik](https://user-images.githubusercontent.com/30140713/184950829-1f07ff27-f1fa-44b3-ac26-629571b1b043.png)
@spi43984 added a that button to ["prelease"](https://github.com/dennisverspuij/tb-correctidentity/releases/tag/latest)

**Comment by spi43984** [comment]
That's cool - thanks!

**Comment by ldreier** [comment]
Included in released version 2.2.1, which is now available on thunderbird addon web site.

**Comment by spi43984** [comment]
Thxs for the release. The quick button works but is blank...
![ci icon](https://user-images.githubusercontent.com/22529093/193776698-ae632e3d-1c1f-4a74-a9d5-22d1af39972f.jpg)

**Comment by ldreier** [comment]
I got this information from the Add-On reviewer together with the release information:

There is a bug in 102: The new action button will not appear for old users, only for fresh installs. You might get user feedback which is caused by this. Solution: Remove add-on, restart, re-install add-on. We will fix that.

**Comment by spi43984** [comment]
> There is a bug in 102: The new action button will not appear for old users, only for fresh installs. You might get user feedback which is caused by this. Solution: Remove add-on, restart, re-install add-on. We will fix that.

Did that. removed add-on, restarted TB, re-installed add-on. Icon is to see but still blank. Am on TB 91.11.0 on Linux.

**Comment by spi43984** [comment]
> > There is a bug in 102: The new action button will not appear for old users, only for fresh installs. You might get user feedback which is caused by this. Solution: Remove add-on, restart, re-install add-on. We will fix that.
> 
> Did that. removed add-on, restarted TB, re-installed add-on. Icon is to see but still blank. Am on TB 91.11.0 on Linux.

Works with TB 102 now.
