### ISSUE TITLE
BUG: Identity Selection Ignored when Account Alias is Used

### ISSUE THREAD

**Issue by ladar** [dennisverspuij/tb-correctidentity#24]
I have an account configured with two email addresses (in this case the same mailbox, but with two different domain names). Whenever I try to forward messages, and one of those messages was addressed to the alternate domain name, the alternate address is automatically selected. This is what triggers the bug... that's because have the plugin setup to detect messages addressed to specific domains, and if detected, switch the sending account, In this case its being switched to a completely different account, and not just an alias. This works perfectly whenever I forward messages addressed to the default account identity. But whenever the alias is in use, the rule gets ignored.

Let me know if you need more clarification.

**Comment by ldreier** [comment]
@ladar
Indeed, I need some clarification.
Maybe to align some general questions: 
- Which addon-version are you using?
- Which Thunderbird version are you using

My understanding of your account/identity configuration is something like this:
-account1
  - identity1
  - identity2
-account2
  - identity3

Your correct identity configuration is:
For "Selection":
-account1: "attempt to find and use an identity that appears in its recipient list" is selected

You have a mail in your inbox with e.g.
"To: identiy2"
"From: someExternaIIdentity"
...and you click on "Forward" ... then "identity2 (account1)" should appear as "from:"?
This is at least what happens in my tests.

What is the difference?
- do you have addon (for correct identity) configurations for the "account2", which cause side effects?
- do you use another addon (e.g. OWL) which may modify the acoounts/identies at runtime?

**Comment by ladar** [comment]
@ldreier 

>     * Which addon-version are you using? 
>     * Which Thunderbird version are you using

I have lots of different systems, but the dev machine I have closest to me at the moment is running with TB version 102.5.0 and this TB install only has 2 plugins installed. Correct Identity version 2.2.1 and Identity Chooser version 3.2.
 
> My understanding of your account/identity configuration is something like this: -account1
> 
>     * identity1
>     * identity2
>       -account2
>     * identity3
> 

You might be a little off. It might be more accurate to say:

* account 1 / identity 1
  - alias 1 linked to account 1 (uses account 1 SMTP config, but with alternate From address)
* account 2 / identity 2
* account 3 / identity 3

> Your correct identity configuration is: For "Selection": -account1: "attempt to find and use an identity that appears in its recipient list" is selected

My rules are setup so that whenever a specific email address is entered into the list of recipients, the account will automatically switch to using account 3 / identity 3. In my case I need to forward spam using the account 3/identity 3 because that SMTP server doesn't have virus scanning enabled on outbound messages. If I try to use the SMTP server associated with account 1 / identity 1, it's almost certain that the message will get blocked because if you have more than a dozen or so spams attached, at least one is bound to trigger the virus scanner. And figuring out which message is causing the problem so it can be removed is a huge pain. Correct identity solves this problem (along with other problems) for me.

To put what I'm trying to say another way, if I select a message from account 1 and try to  forward it, a compose window will open with account 1 / identity 1 selected as the from address. As soon as I enter the specific recipient address I've configured the seopsoqn switches to using the identity 3 which also means the message will be sent using the SMTP server for account 3. Of course if I don't enter this specific recipient, then a message will go out using account 1 / identity (provided I don't manually change it). 

Now comes the edge case. If one of the messages I select to forward is addressed to the alias associated with account 1, then the compose window opens with the alias selected as from address instead of suing identity 1. This behavior is triggered by the TB setting that caues replies/forwards to go out using the same from address (or account) they arrived for. This scenario is also what triggers the bug: as the account/identity do not automatically switch to using account 3/identity 3 when I enter the matching recipient.

> You have a mail in your inbox with e.g. "To: identiy2" "From: someExternaIIdentity" ...and you click on "Forward" ... then "identity2 (account1)" should appear as "from:"? This is at least what happens in my tests.
 
> What is the difference?
 
I'll try adding fake names/domains it easier to understand:

* account 1 = person@example.com
  - alias 1 = person@exampleinc.com
 * account 2 = info@example.com
 * account 3 = person@devsandboxserver.com

If a message being forwarded was delivered to person@exampleinc.com then that gets picked as the default from address, and the correct identity rules aren't being applied.

Is this making sense? If not I record a video showing this issue. It would just be a huge pain to setup this scenario on system without any real data or private info. And I'm not keen on recording any of the setups I have with real email accounts configured.

**Comment by ldreier** [comment]
OK ... I think I now understand your issue...

Seems that this is a side effect of the prioritization in 
[background-script.js#L433](https://github.com/dennisverspuij/tb-correctidentity/blob/d5445b6dc92153e346fc1df4198f9efa6dab70fa/scripts/background-script.js#L433)
which is always applied not taking into account if the compose tab is opened for the first time (clicking "forward") or if you later enter a recipient.

I think this could be changed, but I am not yet sure if this should be changed in general or if it break some uses cases for other users. I will have a look on this and will come back with a proposal or code change.

**Comment by ladar** [comment]
@ldreier are you saying you still can't replicate this issue? The key is having an account setup with TWO FROM addresses. So add the alias person@exampleCORP.com to the  person@exampleINC.com  account. And create a message addressed to  person@exampleCORP.com. When you attempt to forward the message addressed to the alias, or a group of messages containing a message addressed to person@exampleCORP..com ... then  person@exampleCORP.com will be selected as the from address. In this scenario when you enter the to address, the detection rule DOES NOT get applied.

**Comment by ldreier** [comment]
@ladar your last comment was not fully consistent with your earlier comment (e.g. on Dec 8, your account1 has "[person@example.com](mailto:person@example.com)" as default identity while it is now "[person@exampleINC.com](mailto:person@exampleINC.com)". So that did not help.

To get a behavior similar to your description in my test setup, I put the test-message in the Inbox of a second account. In that case Thunderbird does not interfere with the from-address selection an the addon selects the initial from address. Here we have the situation as described in my post on Dec 13.

I modified the addon as proposed on Dec 13.

New behavior: The from-address-selection priorities are changed after the reply/forward window is opened and the initial from-address is selected.
Initially the priorities are:
1. based on original message recipients if configured for that account in the addon)
2. configured from-address (in the addon) for that account
3. detection aliases /additional header fields from the addon config
4. default identity from Thunderbird

If 1) has a match on opening the message, this is used to select the from-identity. Then the priorites are changed:
1. configured from-address (in the addon) for that account
2. detection aliases /additional header fields from the addon config
3. based on original message recipients if configured for that account in the addon)
4. default identity from Thunderbird

The changes are available in the current "latest" addon: [LINK to XPI](https://github.com/dennisverspuij/tb-correctidentity/releases/download/latest/correct_identity_latest.xpi)

Could you please check, if this addresses your problem.

**Comment by ladar** [comment]
> @ladar your last comment was not fully consistent with your earlier comment (e.g. on Dec 8, your account1 has "person@example.com" as default identity while it is now "person@exampleINC.com". So that did not help.

My apologies. I think I switched up the references to try and match the names you were using. And when I finished writing my last post, I was planning to send you screenshots and/or a short video clip privately to illustrate. But couldn't (easily) find your email address, and started setting up a VM a with dummy accounts, so I could post the images here, but ran out of time, and haven't gone back to it. I often end up in LIFO mode.

> The changes are available in the current "latest" addon: LINK to XPI ... Could you please check, if this addresses your problem.

I'm have v2.2.1 installed so, I'll update now test.

**Comment by ladar** [comment]
@ldreier I've only tested the fix once, so my sample size is limited, but it WORKS as expected now. Thank you.

This computer has Thunderbird 102, and the Correct identity plugin was built from source, using the 60cdd419b4d97304541cf94c68b826e05101a934 commit.

Your GitHub profile is pretty slim, and I couldn't find an obvious donation link for the project. So in lieue of the few dollars I would have sent, I'll just have to say THANK YOU. Rather I shouild I say, @ldreier, if I can return a comparable favor in the future please let me know.
