### ISSUE TITLE
confirmation pop-up on wrong display in multi-display setup

### ISSUE THREAD

**Issue by spi43984** [dennisverspuij/tb-correctidentity#29]
I am using Correct Identity 2.2.1 on TB 102.9.0 on Ubuntu 20.04. I have a notebook connected to an external monitor. The external monitor is the main display.

In case I start TB on the external display, the CI confirmation pop-up to send emails to a (unknown or unconfirmed) recipient is shown on the external (i. e. main) display.

As soon I disconnect the external display (and let TB open) from the notebook the TB window is moved to the notebook display. When I reconnect the external display and move the TB window from the notebook display to the external one, the  CI confirmation pop-up still keeps showing on the notebook display. I need to shut TB and restart it on the external display to have the confirmation pop-up be shown on the external display.

I'd expect the confirmation pop-up to be shown on the same display TB is shown on.

**Comment by ldreier** [comment]
Hi @spi43984,

when trying to reproduce the issue, I failed to find the pop-up you mentioned. I think there is no "unknown or unconfirmed recipient" pop-up in correctidentity?! Could you give some exact text or screenshot of the pop-up?

I have the feeling that this is maybe a general Thunderbird issue. (The addon is using "[windows.create(...)](https://webextension-api.thunderbird.net/en/latest/windows.html#create-createdata)" with left and top not set)

**Comment by spi43984** [comment]
It's that pop-up...

![ci](https://user-images.githubusercontent.com/22529093/233577253-cb3f7194-03b3-459f-aca9-568d78348a3f.jpg)

**Comment by spi43984** [comment]
Forgot to mention - when composing a new mail in TB by ctrl-n, TB shows the new message window on the same display as its main window. Only the pop-up is shown on another display.

**Comment by ldreier** [comment]
For information: Issue can now be reproduced in the test setup.

I have the feeling that this is somehow related to
[https://bugzilla.mozilla.org/show_bug.cgi?id=1812262](https://bugzilla.mozilla.org/show_bug.cgi?id=1812262)
This fix is not yet in the current release version of Thunderbird. (It is in the beta test versions)
I am not sure if this fixes the issue or just enable to fix it from the addon-side... need to test those.

**Comment by spi43984** [comment]
Thanks for letting me know.
I can help testing as soon fix is available, just drop me a note.

**Comment by ldreier** [comment]
Hi @spi43984,

a fix is provided in https://github.com/dennisverspuij/tb-correctidentity/releases/tag/v2.2.2_rc1
Unfortunately you also need a Thunderbird beta version >=112 (tested with 113.0b4).
The Thunderbird fix mentioned above should be included in the next release of Thunderbird 115,
scheduled for July 2023.
(see also commit message for details)

**Comment by spi43984** [comment]
> a fix is provided in https://github.com/dennisverspuij/tb-correctidentity/releases/tag/v2.2.2_rc1
> Unfortunately you also need a Thunderbird beta version >=112 (tested with 113.0b4).
> The Thunderbird fix mentioned above should be included in the next release of Thunderbird 115,
> scheduled for July 2023.

Thanks for fixing this. Not sure I can set up TB beta to verify the patch. Let's see.

**Comment by spi43984** [comment]
Checked bugfix with TB beta release 113.0b5 - can confirm that webextension popup dialog is shown on the correct screen now.
