### ISSUE TITLE
[Feature Request] Write correct Identity into Carddav

### ISSUE THREAD

**Issue by Mannshoch** [dennisverspuij/tb-correctidentity#3]
I use Thunderbird on several PC and wish a identical use of the Identity. Please save this information per e-Mail Address into CardDAV. Maybe work together with CardBook which is my address book and do the connection to CardDAV. I opened a similar Issue in [CardBook](https://gitlab.com/CardBook/CardBook/issues/152)

**Comment by dennisverspuij** [comment]
Hi, I understand your use case, configuring preferred identity to use for a specific contact in your address book. Identification of such identity should then be based on email address of the identity, in order for different clients to support given carddav entries. But I doubt there are any clients yet that support it or will support it, TB would be the first only when using CardBook and Correct Identity together. Imho too much work for small number of users. I think you'd be better of with [Virtual Identity](http://www.absorb.it/virtual-id). You can configure it to learn what identity you want to use for what recipient, e.g. the first time you send an email to X it will remember the selected identity and will automatically select that identity next time you send to X. You can also import/export the preferences so you can sync between multiple TB clients. If ever CardBook would implement your request please remind me and I will reconsider.
