### ISSUE TITLE
Minor spelling issue - german

### ISSUE THREAD

**Issue by teatower** [dennisverspuij/tb-correctidentity#30]
There is only one correct spelling für the electronic mail in german "E-Mail".
Email is a material dishes are made from.

**Comment by ldreier** [comment]
Fixed with [commit 3ce10f76](https://github.com/dennisverspuij/tb-correctidentity/commit/3ce10f76238ac4316d1b782e7fe7f867aaf04ff4)

**Comment by ldreier** [comment]
Fix is part of Release v2.3.2
