### ISSUE TITLE
Text in Preferences panel does not wrap correctly

### ISSUE THREAD

**Issue by akwala** [dennisverspuij/tb-correctidentity#34]
Correct Identity 2.3.2
Thunderbird 115.3.1
Kubuntu 22.04

See screenshot below. This is also the case for the text in the on-hover popups (orange background) for the search terms input boxes.

![Screenshot_20231006_163950](https://github.com/dennisverspuij/tb-correctidentity/assets/1786/1a08c91c-1a8d-44c8-850a-99ff3a101f6a)

**Comment by ldreier** [comment]
On my system (also KDE based) I see a horizontal scrollbar appearing when width of the window is reduced beyond a certain point.
Is the scrollbar missing in your system? Or do you think the scrollbar appears too early?

**Comment by akwala** [comment]
> On my system (also KDE based) I see a horizontal scrollbar appearing when width of the window is reduced beyond a certain point. Is the scrollbar missing in your system? Or do you think the scrollbar appears too early?

Yes, there is a horizontal scrollbar at the bottom but, with my window size, I have to scroll down to see it, which is why I didn't see it before.

However, to read text spanning multiple lines, one has to scroll back and forth which makes it difficult to read, as can be seen in the screenshot below. To see the entire width of the on-hover popups, the scrollbar has to be in that position; if it is a little to the right or left of that position, the full width of the popups is not visible.

Ideally, the text would wrap at, or within, the boundary of the pane, so that scrolling isn't needed. I'm not sure if this can be controlled.

**Comment by ldreier** [comment]
The change mentioned above is included in v2.4.0, which is now available from Thunderbird add-on page as latest version.

**Comment by akwala** [comment]
Confirming that it's fixed in v.2.4.0.
