### ISSUE TITLE
Protection of Identinty does not work with keyboard-shortcuts Ctrl+Enter and Ctrl+Shift+Enter

### ISSUE THREAD

**Issue by WalZyl** [dennisverspuij/tb-correctidentity#40]
Warning me/sender before sending a message from an identity if its recipients match one or more search terms does _not_ work when using keyboard-shortcut Ctrl+Enter and Ctrl+Shift+Enter. It works well when using the Send button located at the top-left corner (Windows).

Is there any chance to extended the hook behind the Send button to the keyboard-shortcuts Ctrl+Enter and Ctrl+Shift+Enter?

Version of add-on: "latest", i.e. with the extension to (more than one) address books

**Addition**: Just noted that in the following case even the Send button does not work.
To: Kassierer@domain.net

Search term is one of the following:
Kassierer@domain.net - does not work as expected, no notification after pressing Send button
Kassierer                      - see above
kassierer                      - notification in a window (note however that this is not case sensitive)

However, is using regexp instead:
/[kK]assierer@domain.net/  - works with the Send button AND the keyboard shortcuts
/[kK]assierer/                      - works with the Send button AND the keyboard shortcuts

**Conclusion**: there is a hook to the shortcuts; use regexp -> Solved. Pattern are not case sensitive -> remain issue.

**Comment by ldreier** [comment]
I did some checks ... seems that the check is only half "case insensitive". I.e. the email addresses in the mail are converted t lower-case when comparing. But the configured match patterns are not...
So as a workaround the match pattern should be lower case.
@WalZyl , could you check and confirm that this works in your case?

**Comment by WalZyl** [comment]
Assuming: To: Kassierer@domain.net

Kassierer@domain.net, Kassierer - do not work
kassierer@domain.net, kassierer - do work
/[kK][assierer@domain.net/, /[kK]assierer/ - do work

Conclusion based on this examples: currently case insensitive; workaround: use regexp or lower case letters as patters, which confirms your checks. Thanks for quickly responding!!

**Comment by WalZyl** [comment]
@ldreier : I played around with the address-book possibilities (#33), which are very useful in general. I suggest you put this on the add-on "advertisement" page. 

Due to the workaround ("So as a workaround the match pattern should be lower case.", see above) every eMail address needs to be lower case in order to work - however, folks are writing capital and lower case and mixed, and TB is collecting this as is, which users use to fill address books. 

I need to convert - by hand - every eMail address in a address book to lower case which renders this add-on in this development stage as hard to accept. Please, make the checks **full case insensitive**  , if you find some spare time, soon. Thx.
