### ISSUE TITLE
TB v.128

### ISSUE THREAD

**Issue by siffegh** [dennisverspuij/tb-correctidentity#41]
Please update for TB v.128.

**Comment by ldreier** [comment]
... was already planned, but test framework needs update... finished today. Tests passed for Thunderbird Version 128esr.
Manifest was updated and release in [v2.4.1](https://github.com/dennisverspuij/tb-correctidentity/releases/tag/v2.4.1).
This version is also submitted for Release via "Thunderbird-Add-ons"

**Comment by siffegh** [comment]
Thank you.
