### ISSUE TITLE
Manage identity taken from "X-Apparently-To" header added by yahoo

### ISSUE THREAD

**Issue by tenzap** [dennisverspuij/tb-correctidentity#7]
I'm using the "disposable address" feature of Yahoo mail.

With this feature, Yahoo adds a header to all incoming messages containing the email to whom the email has been sent to. For example :
**X-Apparently-To:** basemail-extension@yahoo.tld; Fri, 28 Dec 2018 17:41:29 +0000

Whenever I reply to such an email, I want my sender email in the reply set to the one on which I received it.

You will find attached a patch to the version 1.4.8 of correct-identity which will
- create an identity having the email in X-Apparently-To if it doesn't already exist, by copying the default identity of the server
- set the identity of the reply to the one in X-Apparently-To

So that it does work, thunderbird must be able to read that specific header. This can be achieved either by installing enigmail, or by adding this line to your preferences (file: prefs.js) .
_user_pref("mailnews.headers.extraExpandedHeaders", "X-Apparently-To");_

[correctIdentity-1.4.8-2018-12-28-tb60.patch.gz](https://github.com/dennisverspuij/tb-correctidentity/files/2715397/correctIdentity-1.4.8-2018-12-28-tb60.patch.gz)

**Comment by dennisverspuij** [comment]
Hi tenzap, thanks for your contribution! I am sure it is a useful addition for users of Yahoo disposable addresses, but it is also a very specific use case, and doing something my extension has not done before (creating identities). As such your patch mainly adds a new overlay doing something independent of existing code. Therefore I recommend creating another extension for this. And e.g. make the header name configurable so users can use other disposable header providers as well.
