### ISSUE TITLE
Correct Identity NW when replying to all from own message-needs to look in SENDER 1st!

### ISSUE THREAD

**Issue by piecevcake** [dennisverspuij/tb-correctidentity#8]
As per subject line above

- easy to resolve? look in SENDER before look in recipients, if identity found in sender, use that as sender 

Helpful but not essential- then remove that sender from recipients. (even more helpful=remove UNLESS sender is BCC'd in original message)

:-)
Vicki
![thunderbird correct identity putting wrong sender in reply  @2019 03 09, 11_36_57](https://user-images.githubusercontent.com/32110576/54061690-c9212200-4266-11e9-9f2e-d7ad42460b22.png)

**Comment by dodmi** [comment]
I'm not really sure, if it is the same issue, which I had: https://github.com/dennisverspuij/tb-correctidentity/issues/1#issuecomment-719994469

And I'm almost sure, I found the solution too late for you...
