### ISSUE TITLE
Update for Thunderbird 68.0?

### ISSUE THREAD

**Issue by sbaum** [dennisverspuij/tb-correctidentity#9]
Hi, yesterday TB 68.0 has been released. It would be a pity if there was no compatible version of this great plugin. May we hope?

**Comment by bit** [comment]
created pull request #10 to fix

**Comment by axb-lists** [comment]
What do we need to do to apply this fix?
(need cluebat :)

**Comment by rajokon** [comment]
> 
> 
> What do we need to do to apply this fix?
> (need cluebat :)

1. Copy the _correct_identity-1.4.8-tb.zip_ from [https://github.com/dennisverspuij/tb-correctidentity/pull/4#issuecomment-427641246](https://github.com/dennisverspuij/tb-correctidentity/pull/4#issuecomment-427641246)
2. extract the _correct_identity-1.4.8-tb.xpi_ and rename it to **correct_identity-1.4.8-tb.xpi.zip** (you see the .zip behind the .xpi)
3. inside the **correct_identity-1.4.8-tb.xpi.zip**, create an empty file named manifest.json and insert the code from [https://github.com/dennisverspuij/tb-correctidentity/pull/10/files#diff-4b1eb3dc48c4e16d49db5b42298fe654](https://github.com/dennisverspuij/tb-correctidentity/pull/10/files#diff-4b1eb3dc48c4e16d49db5b42298fe654) in it.
4. maybe, you don't need this step: delete inside **correct_identity-1.4.8-tb.xpi.zip** the file _install.rdf_
5. rename the **correct_identity-1.4.8-tb.xpi.zip** back to _correct_identity-1.4.8-tb.xpi_ an install the AddOn manually

**Comment by axb-lists** [comment]
HUGE THANKS!   That was magic :)
(I did not need to delete the install.rdf file)
Again, thanks for your help!

**Comment by f03el** [comment]
I got it installed in TB 68.1.2 by adding `manifest.json` to the xpi file, but addon settings are not saved. Every time I open the settings, they have been reset to the defaults.

**Comment by dougbreaux** [comment]
My settings aren't saving either, but even worse, the detection doesn't seem to be working at all. I really thought it was at some point, but it's clearly not with an email I'm replying to right now.

**Comment by axb-lists** [comment]
> HUGE THANKS! That was magic :)
> (I did not need to delete the install.rdf file)
> Again, thanks for your help!

Followup: Settings are not being stored and detection seems broken. Apparently there's more to it than just the manifest file

**Comment by SimonMaenaut** [comment]
For everyone looking for a Thunderbird 68 compatible version https://github.com/rwg0/tb-correctidentity/tree/tb68 works and has fixes for detecting the identities in recipients and saving settings.
Looking forward for these fixes to come up-stream and hopefully see a new release!

**Comment by alexolog** [comment]
I prefer https://github.com/tenzap/tb-correctidentity as it uses X-apparently-to which is, in my opinion, the most reliable detection method

**Comment by michaelletzgus** [comment]
Thanks a lot for the TB68 versions, they work great.
One small problem: The detection an usage of an account's default address does not work.
If "use accounts default" is select thunderbird uses always the same (first?) account. When selecting  an address manually for a given account everything works fine.

**Comment by michaelletzgus** [comment]
Another even smaller problem: The textboxes for entering mail addresses in settings are constantly 3 rows high. No scrollbar, no scaling with dialog size.

**Comment by Robert080** [comment]
I'm desperatelly looking for a functionally version of this extension. I've not undestood how to download the file.

**Comment by yennor** [comment]
@Robert080
I'm using following version, which is working for me:
https://github.com/tenzap/tb-correctidentity/tree/tb68-XApparentlyTo

- There click on  "clone or download" 
- choose download zip
- open the zip file. Everything will be below the directory "tb-correctidentity-tb68-XApparentlyTo". Move it up one directoy level and then delete the directory "tb-correctidentity-tb68-XApparentlyTo".
- rename the *.zip file to *.xpi
- add it to thunderbird in the add on menu.

=> et voila :-)

**Comment by Robert080** [comment]
Thank you very much. I've been able to intall the extension but only deleting the "install.rdf" file and after adding "manifest.json" file. Actually using in TB 68.8 version

**Comment by ygrange** [comment]
Looks like this version already have a manifest.json, but thunderbird complains it is invalid. I'll have a look at it and report back if I find what is wrong there...

**Comment by ygrange** [comment]
One more question on this. I managed to install the addon in my TB using this thread, but now I realise I want to edit my configuration. And it seems like I cannot find the configuration anywhere in the TB menu structure. Any idea where I could find it?

**Comment by jouffrais** [comment]
Hi everyone
Do you know if there is a fix for TB78 on Windows? I really miss that extension!
Thanks
